# constants.py
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN = 0.3

# Shield / power-up constants
SHIELD_RADIUS = 15
SHIELD_DURATION = 10.0  # seconds the shield lasts once picked up
POWERUP_SPAWN_RATE = 10.0  # seconds between attempts to spawn a power-up
